examples: fix building with C allocator
Usage of C allocator requires linking libc, but previously
build system did not link it, and this caused error like below:

```zig
/usr/lib64/zig/9999/lib/std/heap.zig:37:13: error: C allocator is only available when linking against libc
            @compileError("C allocator is only available when linking against libc");
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib64/zig/9999/lib/std/c/linux.zig:289:12: error: dependency on libc must be explicitly specified in the build command
pub extern "c" fn posix_memalign(memptr: *?*anyopaque, alignment: usize, size: usize) c_int;
```

After this commit examples build again.

Signed-off-by: Eric Joldasov <bratishkaerik@getgoogleoff.me>